### ISSUE TITLE
Błąd przy zamykaniu okna konfiguracji

### ISSUE THREAD

**Issue by piotrkot** [piotrkot/jpk-vdek#10]
Zamykanie konfiguracji programu przyciskiem z opisem "close" na dole wywołuje błąd:

java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.setBindings(javax.script.Bindings, int)" because "this.scriptEngine" is null
        at org.apache.pivot.beans.BXMLSerializer$AttributeInvocationHandler.invoke(BXMLSerializer.java:154)
        at com.sun.proxy.$Proxy4.buttonPressed(Unknown Source)
        at org.apache.pivot.wtk.Button$ButtonPressListenerList.buttonPressed(Button.java:194)
        at org.apache.pivot.wtk.Button.press(Button.java:412)
        at org.apache.pivot.wtk.PushButton.press(PushButton.java:70)
        at org.apache.pivot.wtk.skin.PushButtonSkin.mouseClick(PushButtonSkin.java:77)
        at org.apache.pivot.wtk.skin.terra.TerraPushButtonSkin.mouseClick(TerraPushButtonSkin.java:591)
        at org.apache.pivot.wtk.Component$ComponentMouseButtonListenerList.mouseClick(Component.java:503)
        at org.apache.pivot.wtk.Component.mouseClick(Component.java:2860)

Zamknięcie okna za pomocą "X" w narożniku nie powoduje błędu. - użytkownik

**Comment by piotrkot** [comment]
Błąd może być w bibliotece apache pivot lub wersji jdk. W tym przypadku używana jest wersja
"openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)"
Środowisko Windows 10.

W wersji jdk1.8.0_191 (Linux) i java-1.11.0-openjdk-amd64 (Linux) problem nie występuje.

Na szczęście zamknięcie okna błędu pozwala kontynuować pracę i nie ma innego zauważalnego wpływu na działanie programu.
